DROP TABLE IF EXISTS PASSAGES;
CREATE TABLE PASSAGES (
    SEGMENT INTEGER,
    BUS TEXT,
    CALENDAR TEXT,
    TIMEPASS INTEGER,
    ID SERIAL PRIMARY KEY,

    CONSTRAINT pass_seg_fk FOREIGN KEY (SEGMENT) REFERENCES SEGMENTS(id),
    CONSTRAINT pass_cal_fk FOREIGN KEY (CALENDAR) REFERENCES GTFS.CALENDARS(id)

);

