DROP TABLE IF EXISTS PASSAGES;
CREATE TABLE PASSAGES (
    SEGMENT INTEGER,
    BUS TEXT,
    CALENDAR TEXT,
    TIMEPASS INTEGER,
    ID SERIAL PRIMARY KEY,
    FREQUENCY INTEGER,

    CONSTRAINT pass_seg_fk FOREIGN KEY (SEGMENT) REFERENCES SEGMENTS(id),
    CONSTRAINT pass_cal_fk FOREIGN KEY (CALENDAR) REFERENCES GTFS.CALENDARS(id),
    CONSTRAINT pass_freq_fk FOREIGN KEY (FREQUENCY) REFERENCES GTFS.FREQUENCIES(id)

);

